name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk wget
        pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
        
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

        yes | sdkmanager --licenses
        sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

    - name: Set Environment Variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/build-tools/34.0.0:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug
